version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      ROARR_LOG: true
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - proposals-database:/var/lib/postgresql/data

volumes:
  proposals-database:
